# Generated by Django 4.2 on 2023-05-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('content', models.TextField(verbose_name='Описание(текст)')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроци',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('order', models.SmallIntegerField(blank=True, default=1, verbose_name='Номер')),
                ('picture', models.ImageField(upload_to='article_pics', verbose_name='Снимка/графика:')),
                ('author', models.CharField(max_length=60, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рисунка',
                'verbose_name_plural': 'Рисунки',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('order', models.SmallIntegerField(blank=True, default=1, verbose_name='Номер')),
                ('picture_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Стъпка',
                'verbose_name_plural': 'Стъпки',
            },
        ),
    ]
