# Generated by Django 4.2 on 2023-05-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='picture',
            name='in_gallery',
            field=models.BooleanField(default=True, verbose_name='в галерията'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.picture', verbose_name='Рисунка'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='article_pics', verbose_name='Рисунка(файл):'),
        ),
    ]
