# Generated by Django 4.2 on 2023-05-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_lesson_picture_in_gallery_alter_item_picture_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picture_id',
        ),
    ]
