# Generated by Django 4.2 on 2023-05-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_item_picture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='', upload_to='article_pics', verbose_name='Рисунка(файл):'),
        ),
    ]
