# Generated by Django 4.2 on 2023-05-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(verbose_name='Пояснение'),
        ),
    ]
